In [6]:
import numpy as np
from scipy.sparse import diags
import time 
n=4
k = np.array([-np.ones(n-1),4*np.ones(n),-np.ones(n-1)])
offset = [-1,0,1]
A = diags(k,offset).toarray()
C=diags(k,offset).toarray()
P=list()
L=list()
start=time.time()
#permutation matrix and primary L
for i in range(n):
    I=np.identity(n)
    for j in range(i+1,n):
        if(abs(A[j,i])==max(abs(A[i:,i]))):
            A[[i, j]] = A[[j, i]]
            I[[i, j]] = I[[j, i]]
            P.append(I)
            
    t=np.identity(n)
    for j in range (i+1 , n):
        c=-A[j,i]/A[i,i]
        A[j,:]=c*A[i,:]+A[j,:]
        t[j,i]=c
                
    L.append(t)    
#finding L'    
L_prime=list()
p1=np.identity(n)
p2=np.identity(n)
for i in range(n-1):
    if (P!=[]):
        for j in range(i+1,n-1):
            p1=P[j].dot(p1)
            #print("p1",p1)
            p2=p2.dot(np.linalg.inv(P[j]))
            #print("p2",p2)
    
        T=(p1.dot(L[i])).dot(p2)
        #print(T)
    else:
        T=L[i]
       
    L_prime.append(T)
      
#finding final L    
lf=np.identity(n)
for l in L_prime:
    lf=l.dot(lf)
    #print("lf",lf)
       
L_final=np.linalg.inv(lf)
end=time.time()
print("time:" , end-start)
U=A
print(L_final.dot(U).astype(int))


time: 0.0007085800170898438
[[ 4 -1  0  0]
 [-1  4 -1  0]
 [ 0 -1  4 -1]
 [ 0  0 -1  4]]


<ipython-input-6-76b42a8f16ef>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  k = np.array([-np.ones(n-1),4*np.ones(n),-np.ones(n-1)])
